### Bids of Article
GET http://localhost:8080/api/auctions/1/bids

### Place Bid on Article
POST http://localhost:8080/api/auctions/1/bids
Content-Type: application/json

{
  "amount": 3000,
  "date": "2022-03-26",
  "customer": {
      "id": 3
    }
}

### Get Article
GET http://localhost:8080/api/auctions/1

### Get Articles
GET http://localhost:8080/api/auctions?state=SOLD

